chatapp/urls.py
from django.urls import re_path
from . import views

app_name = 'chats'

urlpatterns = [
    re_path(r'^$', views.app, name='twilio'),
    re_path(r'^token', views.token, name='token'),
]

taskapp/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('project/<int:id>/add_task', views.add_task, name='add_task'),
    path('task/<int:id>/edit/', views.task_edit, name='task_edit'),
    path('task/<int:id>/delete/', views.task_delete, name='task_delete'),
    path('project/', views.add_project, name='add_project'),
    path('project/<int:id>', views.project_detail, name='project_detail'),
    path('project/<int:id>/edit', views.project_edit, name='project_edit'),
    path('project/<int:id>/delete', views.project_delete, name='project_delete'),
    path('profile/', views.profile_edit, name='edit_profile'),
    path('login/', views.login_view, name='login'),
    # path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # path('my_tasks/<int:id>', views.my_tasks, name='my_tasks'),
    # path('task/<int:task_id>/user/delete/<int:user_id>', views.delete_user_from_task, name='delete_user_from_task'),
    # path('task/<int:id>/user/add/', views.add_user_to_task, name='add_user_to_task'),
    # path('tasks/available/', views.available_tasks, name='available_tasks'),
]

taskman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('taskapp.urls', namespace="tasks")),
    path('chat/', include('chatapp.urls')),
    path('admin/', admin.site.urls),
]

taskapp/models.py
from enum import Enum

from django.contrib.auth.models import User
from django.db import models
from simple_history.models import HistoricalRecords


class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=1000)
    start_date = models.DateField('Start date')
    competency = models.CharField(max_length=256)


class Project(models.Model):
    name = models.CharField(max_length=256)
    members = models.ManyToManyField(Staff)
    history = HistoricalRecords()

    def __str__(self):
        return self.name


class TaskStatus(Enum):
    CLOSED = "Closed"
    IN_PROGRESS = "In Progress"
    COMPLETED = "Completed"
    TERMINATED = "Terminated"


class Task(models.Model):
    name = models.CharField(max_length=256, default='')
    description = models.CharField(max_length=1024, default='')
    start_date = models.DateField('Start date')
    due_date = models.DateField('Due date')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project')
    staff_pic = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='staff_pic')
    deliverable = models.FileField('Deliverable', blank=True, null=True, upload_to='deliverable/')
    status = models.CharField(max_length=20, choices=[(tag, tag.value) for tag in TaskStatus])
    history = HistoricalRecords()

    def get_status(self):
        if self.status == "TaskStatus.CLOSED":
            return "Closed"
        elif self.status == "TaskStatus.IN_PROGRESS":
            return "In Progress"
        elif self.status == "TaskStatus.COMPLETED":
            return "Completed"
        elif self.status == "TaskStatus.TERMINATED":
            return "Terminated"
        else:
            return ""

taskapp/forms.py
from django import forms
from .models import Staff, TaskStatus


class TaskForm(forms.Form):
    name = forms.CharField(max_length=256)
    description = forms.CharField(max_length=1024)
    start_date = forms.DateField(widget=forms.SelectDateWidget())
    due_date = forms.DateField(widget=forms.SelectDateWidget())
    deliverable = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}),required=False)
    staff_pic = forms.ChoiceField(choices=[(staff.user.id, staff.user.username) for staff in Staff.objects.all()])
    status = forms.ChoiceField(choices=[(tag, tag.value) for tag in TaskStatus])


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=256)
    members = forms.MultipleChoiceField(choices=[(staff.user.id, staff.user.username) for staff in Staff.objects.all()], widget=forms.SelectMultiple(), required=False)


class LoginForm(forms.Form):
    login = forms.CharField(max_length=32)
    password = forms.CharField(widget=forms.PasswordInput())


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Staff
        exclude = ('user',)

taskapp/views.py
from datetime import date

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from taskapp.forms import LoginForm, ProjectForm, TaskForm, ProfileForm
from taskapp.models import Project, Task, Staff


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form['login'].value(), password=form['password'].value())
            if user is None:
                form = LoginForm()
                return render(request, 'tasks/login.html', context={'form': form, 'error_message': 'Login or password '
                                                                                                   'are incorrect'})
            else:
                login(request, user)
                return redirect('tasks:index')
    else:
        form = LoginForm()
    return render(request, 'tasks/login.html', context={'form': form})


@login_required(login_url='/login/')
def logout_view(request):
    logout(request)
    return redirect('tasks:index')

@login_required(login_url='/login/')
def index(request):
    if request.user.is_superuser:
        headings = Project.objects.all()
    else:
        headings = Project.objects.filter(members__in=[request.user.staff])

    data = {cat: Task.objects.filter(project=cat.pk) for cat in headings}
    columns = [data[heading] for heading in headings]
    columns = list(map(lambda x: list(x), columns))
    if columns:
        max_len = len(max(columns, key=len))
        for col in columns:
            col += [None, ] * (max_len - len(col))
        rows = [[col[i] for col in columns] for i in range(max_len)]
    else:
        rows = None

    try:
        tasks_overdue = Task.objects.filter(project__members__in=[request.user.staff], due_date__lt=date.today())
    except ObjectDoesNotExist:
        tasks_overdue = []


    return render(request, 'tasks/bootstrap-index.html', context={
        'headings': headings,
        'rows': rows,
        'tasks_overdue': tasks_overdue
    })


@login_required(login_url='/login/')
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            new_project = Project(name=form['name'].value())
            new_project.save()
            return HttpResponseRedirect('/')
    else:
        form = ProjectForm()
    return render(request, 'tasks/general_form.html', context={'form': form, 'string': 'New project'})


@login_required(login_url='/login/')
def project_detail(request, id):
    project = get_object_or_404(Project, pk=id)
    return render(request, 'tasks/project_detail.html', context={'project': project})


@login_required(login_url='/login/')
def project_edit(request, id):
    project = get_object_or_404(Project, pk=id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, initial={'name': project.name})
        if form.is_valid():
            project.name = form['name'].value()
            project.save()
            return redirect('tasks:project_detail', id=project.pk)
    else:
        form = ProjectForm(initial={'name': project.name})
    return render(request, 'tasks/general_form.html', context={'form': form, 'string': 'Edit project'})


@login_required(login_url='/login/')
def project_delete(request, id):
    project = get_object_or_404(Project, pk=id)
    project.delete()
    return redirect('tasks:index')


@login_required(login_url='/login/')
def profile_edit(request):
    staff = request.user.staff
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=staff)
        if form.is_valid():
            form.save()
            return redirect('tasks:index')
    else:
        form = ProfileForm(instance=staff)
    return render(request, 'tasks/general_form.html', context={'form': form, 'string': 'Edit profile'})


@login_required(login_url='/login/')
def add_task(request, id):
    project = get_object_or_404(Project, pk=id)
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            new_staff_pic = get_object_or_404(Staff, pk=form['staff_pic'].value())
            new_task = Task(name=form['name'].value(), project=project,
                            description=form['description'].value(),
                            start_date=form['start_date'].value(),
                            due_date=form['due_date'].value(),
                            deliverable=form['deliverable'].value(),
                            staff_pic=new_staff_pic,
                            status = form['status'].value()
                            )
            new_task.save()
            return HttpResponseRedirect('/')
    else:
        form = TaskForm()
    return render(request, 'tasks/general_form.html', context={'form': form, 'string': 'New task'})


@login_required(login_url='/login/')
def task_edit(request, id):
    task = get_object_or_404(Task, pk=id)
    if request.method == 'POST':
        form = TaskForm(request.POST, initial={'name': task.name, 'description': task.description,
                                               'start_date': task.start_date, 'due_date': task.due_date,
                                               'project': task.project, 'staff_pic': task.staff_pic,
                                               'deliverable': task.deliverable, 'status': task.status
                                               })
        if form.is_valid():
            new_staff_pic = get_object_or_404(Staff, pk=form['staff_pic'].value())
            task.name = form['name'].value()
            task.description = form['description'].value()
            task.start_date = form['start_date'].value()
            task.due_date = form['due_date'].value()
            task.staff_pic = new_staff_pic
            task.deliverable = form['deliverable'].value()
            task.status = form['status'].value()
            task.save()
            return redirect('tasks:index')
    else:
        form = TaskForm(initial={'name': task.name, 'description': task.description,
                                               'start_date': task.start_date, 'due_date': task.due_date,
                                               'project': task.project, 'staff_pic': task.staff_pic,
                                               'deliverable': task.deliverable, 'status': task.status
                                               })
    return render(request, 'tasks/general_form.html', context={'form': form, 'string': 'Edit task'})


@login_required(login_url='/login/')
def task_delete(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return redirect('tasks:index')

taskapp/templates/tasks/base.html
{% load static %}
<html>
<head>
    <title>Task App</title>
    <link rel="stylesheet" href="{% static 'tasks/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body>
<div class="header">
    <a href="{% url 'tasks:index' %}" class="logo">&#9739; taskman</a>
    {% if user.is_authenticated %}
        <div class="header-right">
        <a href="{% url 'tasks:index' %}">all tasks</a>
{#        <a href="{% url 'tasks:available_tasks' %}">Available tasks</a>#}
{#        <a href="{% url 'tasks:my_tasks' user.pk %}">My tasks</a>#}
        <a href="{% url 'chats:twilio' %}">live chat</a>
        <a href="{% url 'tasks:logout' %}">logout</a>
    {% endif %}
    </div>
</div>

<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

taskapp/templates/tasks/bootstrap-index.html
{% extends 'tasks/bootstrap.html' %}

{% block content %}
    <div class="panel-group" id="accordion">
    {% if headings %}
        {% for category in headings %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#project{{ category.id }}">
                        <span class="glyphicon glyphicon-th-list"></span> PROJECT #{{ forloop.counter }} : {{ category.name | upper }}
                        </a>
                    </h4>
                </div>
                <div id="project{{ category.id }}" class="panel-collapse collapse {% if forloop.first %}in{% endif %}">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Task</th>
                                    <th>PIC</th>
                                    <th>Due</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for row in rows %}
                                {% for task in row %}
                                    {% if task.project.id == category.id %}
                                        <tr>
                                            <td><a href="{% url 'tasks:task_edit' task.id %}">{{ task.name }}</a></td>
                                            <td>{{ task.staff_pic.user.username }}</td>
                                            <td>{{ task.due_date }}</td>
                                            <td><span class="badge">{{ task.get_status }}</span></td>
                                            <td>
                                                <a href="{% url 'tasks:task_delete' task.id %}" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')">
                                                    <span class="glyphicon glyphicon-remove"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                            </tbody>
                        </table>
                    <a href="{% url 'tasks:add_task' category.pk %}" class="btn btn-info" role="button">Add Task</a>


                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        No task assigned
    {% endif %}
	</div>
{% endblock %}

taskapp/templates/tasks/bootstrap.html
<!-- Latest compiled and minified Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
    .alert.alert-server {
      margin-bottom: 0;
      border-radius: 0;
    }
</style>
{% if tasks_overdue %}
<div class="alert alert-danger alert-server" role="alert">
  <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Task Reminder</strong> You have <strong>{{ tasks_overdue|length }}</strong> overdue tasks. Please complete your task or change the due date.
</div>
{% endif %}
<!-- Fixed navbar -->
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'tasks:index' %}">&#9739; taskman</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
{#				<li class="active"><a href="#">Home</a></li>#}
                {% if user.is_authenticated %}
				    <li class="{% if request.resolver_match.url_name == "index" %}active{% endif %}"><a href="{% url 'tasks:index' %}">tasks</a></li>
                    <li class="{% if request.resolver_match.url_name == "add_project" %}active{% endif %}"><a href="{% url 'tasks:add_project' %}">add project</a></li>
				    <li class="{% if request.resolver_match.url_name == "twilio" %}active{% endif %}"><a href="{% url 'chats:twilio' %}">live chat</a></li>
                    <li class="{% if request.resolver_match.url_name == "edit_profile" %}active{% endif %}"><a href="{% url 'tasks:edit_profile' %}">profile</a></li>
                {% endif %}
			</ul>
            {% if user.is_authenticated %}
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">welcome, {{ user.username }} {% if request.user.is_superuser %}(admin){% else %}(staff){% endif %}</a></li>
				<li><a href="{% url 'tasks:logout' %}">logout</a></li>
			</ul>
            {% endif %}
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>
<div class="container">
	{% block content %}
    {% endblock %}
</div>
<!-- end container -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

taskapp/templates/tasks/general_form.html
{% extends 'tasks/bootstrap.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="tasks-title">{{ string }}</h1>
    <form class="general-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="javascript:window.history.back()" class="btn btn-info" role="button">Cancel</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

taskapp/templates/tasks/index.html
{% extends 'tasks/base.html' %}

{% block content %}
    <div class="wrapper">
        <table>
            <tr>
                {% for category in headings %}
                    <th><a class="category" href="{% url 'tasks:project_detail' category.pk %}">PROJECT: {{ category|upper }}</a></th>
                {% endfor %}
                <th><a class="add-category" href="{% url 'tasks:add_project' %}"><i class="material-icons">add_comment</i></a></th>
            </tr>
            <tr>
                <td class="space-row"></td>
            </tr>
            {% for row in rows %}
                <tr>
                    {% for task in row %}
                        {% if task %}
                            <td class="task">
                                <a class="status-button" href="/project/2/edit">{{ task.get_status }}</a><a class="task-link" href="">{{ task.name|default:'' }}</a>
                            </td>
                        {% else %}
                            <td class="empty-task"></td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            <tr>
                <td class="space-row" style="padding: 10px 0"></td>
            </tr>
            <tr>
                {% for i in headings %}
                    <td class="add-task"><a class="task-link" href="{% url 'tasks:add_task' i.pk %}"><i
                            class="material-icons">add</i></a></td>
                {% endfor %}
            </tr>
        </table>
    </div>
{% endblock %}

taskapp/templates/tasks/login.html
{% extends 'tasks/bootstrap.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="wrapper">
        <form class="log-form" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}

taskapp/templates/tasks/project_detail.html
{% extends 'tasks/base.html' %}

{% block content %}
    <p class="tasks-title">About project</p>
    <div class="detail-list">
        <p class="detail-title"><strong>Name:</strong> {{ project.name }}</p>
    </div>
    <div class="buttons">
        <a class="return-button" href="{% url 'tasks:index' %}">Return</a>
        <a class="return-button" href="{% url 'tasks:project_delete' project.id %}">Delete</a>
        <a class="return-button" href="{% url 'tasks:project_edit' project.id %}">Edit</a>
    </div>
{% endblock %}

taskapp/templates/tasks/register.html
{% extends 'tasks/base.html' %}

{% block content %}
    <div class="form">
        {% if error_message %}
            <p class="error-message">{{ error_message }}</p>
        {% endif %}
        <h1>Register</h1>
        <form class="log-form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </div>
{% endblock %}

taskapp/templates/tasks/task_detail.html
{% extends 'tasks/base.html' %}

{% block content %}
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <p class="tasks-title">Information about task:</p>
    <div class="detail-list">
        <p class="detail-title"><strong>Title:</strong> {{ task.task_name }}</p>
        <p class="detail-description"><strong>Description:</strong> {{ task.task_description }}</p>
        <p class="detail-deadline"><strong>Deadline:</strong> {{ task.task_deadline }}</p>
        <p class="detail-users"><strong>Users:</strong></p>
        <ul class="profile-list">
            {% for profile in task.profile_set.all %}
                <li class="profile-on-task">{{ profile.name }}<a class="delete-profile"
                                                                 href="{% url 'tasks:delete_user_from_task' task.pk profile.id %}"><i
                        class="material-icons">delete_outline</i></a></li>
            {% endfor %}
            <li class="profile-on-task"><a class="add-profile" href="{% url 'tasks:add_user_to_task' task.pk %}"><i
                    class="material-icons">add</i></a></li>

        </ul>
    </div>
    <div class="buttons">
        <a class="return-button" href="{% url 'tasks:index' %}">Return</a>
        <a class="return-button" href="{% url 'tasks:task_delete' task.id %}">Delete</a>
        <a class="return-button" href="{% url 'tasks:task_edit' task.id %}">Edit</a>
    </div>
    <div class="comment-div">
        <h3 class="comment-title">Comments</h3>
        {% if comments %}
            <ul class="comment-list">
                {% for comment in comments %}
                    <li class="comment">
                        <strong>Author:</strong> {{ comment.author.name }}><br/>
                        <strong>Date:</strong> {{ comment.date|date:"H:i d F Y" }}<br/>
                        <strong>Content:</strong> {{ comment.comment_text }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="post" class="comment-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add comment</button>
        </form>
    </div>
{% endblock %}